--- 

# This playbook installs Apache on all hosts in the inventory file.
- hosts: all
  become: yes
  tasks:
    - name: install apache and php with package
      package:
        name: 
          - "{{ apache }}"
          - "{{ php }}"
        state: present
      

    # - name: Install Apache      
    #   apt:
    #     name: 
    #       - "{{ apache }}"
    #       - "{{ php }}"
    #     # make sure the version is the latest
    #     state: latest
    #     update_cache: yes
    #   when: ansible_distribution == 'Ubuntu'
    # - name: Install Apache Centos
    #   yum:
    #     name: 
    #       -  "{{ apache }}"
    #       -  "{{ php }}"
    #     state: latest
    #     update_cache: yes
    #   when: ansible_distribution == 'CentOS'
   
    - name: Start Apache Centos
      service:
        name: "{{ apache }}"
        state: started
        enabled: yes
      when: ansible_distribution == 'CentOS'
    
    - name: Open port 80
      firewalld:
        port: 80/tcp
        # permanent: yes
        state: enabled
        # immediate: yes
      when: ansible_distribution == 'CentOS'
        
